version: "3.9"

services:
  api:
    build: ./servidor
    ports:
      - "8001:8001"
    restart: always
    env_file: ./servidor/.env
    networks:
      - backend
  
  postgres:
    image: postgres:16
    container_name: postgres-inventario
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: always 
    environment:
      POSTGRES_PASSWORD: invent@rio#25
      POSTGRES_DB: db_inventario
    networks:
      - backend


  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d/
  #   depends_on:
  #     - api
  #   restart: always
  #   networks:
  #     - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
