name: BACKEND

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  start:
    name: FRONTEND
    runs-on: self-hosted
    # strategy:
    #   matrix:
    #     node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: |
    #     cd cliente
    #     npm ci
    #     npm install
    #     ng build --configuration production
    #     sudo cp -rf dist/ /var/www/inventario

  env:
    name: SET ENV
    needs: [start]
    runs-on: self-hosted
    steps:
      - name: ENV BACK
        #working-directory: ./servidor
        run: |
          touch ./server/.env
          echo "${{secrets.ENV_INVENTARIO_CONTAINERS }}" > ./server/.env

  build:
    name: DEPLOY BACKEND
    needs: [env]
    runs-on: self-hosted
    steps:
      - name: build
        run: docker-compose up --build -d
